#!/usr/bin/env python3
import subprocess
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_MODULE_DIR = _PROGRAM_DIR / "wyoming_onnx_asr"
_TESTS_DIR = _PROGRAM_DIR / "tests"

_FORMAT_DIRS = [_MODULE_DIR, _TESTS_DIR]

subprocess.check_call(["uvx", "ruff", "check", "--select", "I", "--fix"] + _FORMAT_DIRS)
subprocess.check_call(["uvx", "ruff", "format"] + _FORMAT_DIRS)
